### ISSUE TITLE
[US]: View likes and comment count on article cards on homepage

### ISSUE THREAD

**Issue by Annytomica** [Annytomica/kumiko-community-hub#121]
### User Story:
As a **site user** I can **view the likes and comments count for each article on the homepage** so that **I can identify popular articles**

### Acceptance Criteria:
- [x] likes count displayed on articles cards
- [x] comments counts displayed on articles cards

### Tasks:
- [x] create new view for displaying like counts on homepage
- [x] create new view for displaying comment counts on homepage
- [x] add correct html to index.html to display counts
