### ISSUE TITLE
[Chore]: C2.4: Create Initial Milestones

### ISSUE THREAD

**Issue by Annytomica** [Annytomica/kumiko-community-hub#31]
Epic: #5 

### Description:
Create new milestones for MVP submission, first Iteration (set-up), testing deadline and mentor meetings

### Acceptance Criteria:
- [ ] milestone for MVP submission
- [ ] milestone for first iteration (set-up)
- [ ] milestone for mentor meetings
- [ ] milestone for testing
- [ ] milestone for project design

### Resources:
GitHub Issues
