### ISSUE TITLE
[US]: 3.2: Add or update About page

### ISSUE THREAD

**Issue by Annytomica** [Annytomica/kumiko-community-hub#74]
### User Story:
As a **Site Admin** I can **add or update About content** so that *information about the site is available to view**

### Acceptance Criteria:
- [x] when logged in as Site Admin can access the about app from the admin page
- [x] can add or edit content to about page
- [x] can upload or remove image(s)

### Tasks:
- [x] #79 
- [ ] Task 2
- [ ] Task 3
