### ISSUE TITLE
[US]: 5.2: Add or update Contact page

### ISSUE THREAD

**Issue by Annytomica** [Annytomica/kumiko-community-hub#76]
### User Story:
As a **Site Admin** I can **add or update contact content** so that *information about the feedback the site would like is available to view**

### Acceptance Criteria:
- [x] when logged in as Site Admin can access the about app from the admin page
- [x] can add or edit content to contact page
- [x] can upload or remove image(s)

### Tasks:
- [x] #80 
- [x] #81 
- [ ] #
