### ISSUE TITLE
[US]: 1.1: Account Registration

### ISSUE THREAD

**Issue by Annytomica** [Annytomica/kumiko-community-hub#8]
### User Story:
As a **Site User** I can **register an account** so that **I can comment on articles and submit projects and comment on other users projects**

### Acceptance Criteria:
- [x] User can register account using email address
- [x] Once registered user can login
- [x] When logged in user can comment on articles
- [x] When logged in user can like articles

### Tasks:
- [x] #50  
- [x] #51 
- [x] #52 
- [x] #55
