### ISSUE TITLE
[US]: 2.1 View paginated list of articles

### ISSUE THREAD

**Issue by Annytomica** [Annytomica/kumiko-community-hub#9]
### User Story:
As a **Site User** I can **view a paginated list of articles** so that **I can select which article to view**

### Acceptance Criteria:
- [x] Can open articles page to view articles
- [x] When more than one article in database, these articles are listed
- [x] When on home page can see all article titles with pagination to select what to view

### Tasks:
- [x] #39 
- [x] #46 
- [x] #67
